[package]
name = "shellcode-rs"
version = "0.1.0"
authors = ["Kyle Willmon <kylewillmon@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0"
windows = "0.17.2"

[dependencies]
windows = "0.17.2"
clap = "2.33.3"